### ISSUE TITLE
Code failed when try to import dxc ai - bug level : Blocker

### ISSUE THREAD

**Issue by aumerhadi** [dxc-technology/DXC-Industrialized-AI-Starter#106]
**Describe the bug**
The code fails when I run the part responsible for importing ai from DXC (from dxc import ai)

**To Reproduce**
1. pip install DXC library (First block of code) 
2. run the second block of code (from dxc import ai)

**Expected behavior**
The code should import the ai from DXC library without any issue

**Screenshots**
![image](https://user-images.githubusercontent.com/2063075/115300568-1d797a00-a12e-11eb-9628-5f70bf47aa7c.png)

**Additional context**
Non

**Comment by npulagam** [comment]
When I try to import dxc ai, it is working fine for me, and not able to reproduce the issue. After installing the DXC-Industrialized-AI-Starter try to restart the run-time and then import the dxc ai package.
