### ISSUE TITLE
Is it possible to include a function to test api keys for Mongodb?

### ISSUE THREAD

**Issue by Amar244** [dxc-technology/DXC-Industrialized-AI-Starter#11]
I am just wonder how do i test the api keys obtained from Mongodb using this library. Is it included in it ? 

Where i refer to test what it meant is to check if the api keys are working and able to successfully establish a connection.

**Comment by madhubandru** [comment]
Hi, we have tested mongoDB connection and able to write cleaned raw data into database. You can have a look at test case under Tests>>Automate Test cases>>test_ai.py

Revert to us in case of any questions.

**Comment by Amar244** [comment]
I saw the code below in test_ai.py. It seems if for any reason the connection things didn't workout it will print mongodb connnection failed. I am looking for something to test api keys specifically. 

Let's say before starting a project i want to ensure my keys are working. I import the ai library...i don't have the dataset yet. How do i test my keys in this scenraio.

<i>Note :</i> Assuming i understood below code correctly. 

```
    try:
        wrt_raw_data = ai.write_raw_data(data_layer, raw_data, date_fields)
    except:
        print('----------MONGODB CONNECTION FAILED----------')

```

**Comment by npulagam** [comment]
Hello @Amar244.  You can use below code snippet to check MongoDB connection.

```
from pymongo import MongoClient
client = MongoClient("mongodb://{user}:{password}@{host}:{port}")
db = client.{database}
try: db.command("serverStatus")
except Exception as e: print(e)
else: print("You are connected!")
client.close()
```
In our test cases we are focusing on complete end to end testing in MongoDB data insertion.  When we run our tests then automatically it will take care about this connection string also.

If you have any doubts in using above code snippet, please reach out to me I can help you.

**Comment by Amar244** [comment]
Hi , 

If i understand correctly the above code works if you have a password and a username. However i do believe this AI Library takes api keys as input to connect to the server. i am looking for something like ai.test_keys() method or function to return True or False if my keys are working and able to reach the server.

**Comment by Amar244** [comment]
Hi @npulagam ,

The code you presented seems to provide a way for me to test to my connection. 

Thank you. 

```
from pymongo import MongoClient
client = MongoClient("mongodb://{user}:{password}@{host}:{port}")
db = client.{database}
try: db.command("serverStatus")
except Exception as e: print(e)
else: print("You are connected!")
client.close()

```
