### ISSUE TITLE
[BUG] Loose Dependency Resolver Constraints 

### ISSUE THREAD

**Issue by lrwilt** [dxc-technology/DXC-Industrialized-AI-Starter#131]
**Describe the bug**
Pip install DXC_Industrialized_AI_Starter-2.3.9-py3-none-any.whl takes several minutes and times out in Google Colab due to multiple versions of libraries being downloaded

**To Reproduce**
run pip install

**Expected behavior**
The starter to load in at the most 10 minutes

**Screenshots**

**Additional context**

**Comment by npulagam** [comment]
Hi Logan,

In order to minimize the installation time, we are currently working on optimizing the code and reducing the dependencies. Once we are done with the changes then we will update you. Thank you!

**Comment by npulagam** [comment]
Hi Logan, 

We have optimized the installation time and released the stable version. 

Thanks,
Kishor

**Comment by lrwilt** [comment]
Fantastic! @jerryaoverton and I will check it out. :)
