### ISSUE TITLE
Refactoring the code into sub modules 

### ISSUE THREAD

**Issue by karthikreddykuna** [dxc-technology/DXC-Industrialized-AI-Starter#3]
Refactor the initial version of the code into sub modules.

**Comment by Likhil** [comment]
Code refactoring is done.
Changes are presently available at (https://github.com/karthikreddykuna/DXC-Industrialized-AI-Starter) GitHub repository. We will push the changes to DXC-Industrilialized-AI-Starter main repository after completion of Boot camp.
