### ISSUE TITLE
Verbose and succinct mode for running an experiment

### ISSUE THREAD

**Issue by jerryaoverton** [dxc-technology/DXC-Industrialized-AI-Starter#4]
By default ai.run_experiment() produces a lot of output. Can we add a parameter to the function that defines a verbose and succinct mode? In verbose mode, the function produces the full output, but in succinct mode, only a summary is output. I recommend making succinct mode the default.

**Comment by karthikreddykuna** [comment]
Hi Jerry,
Verbose changes are done for running an experiment. New parameter "verbose" was added to the function with default value as "False". 

Function -> ai.run_experiment(experiment_design, verbose = False)
verbose = False -> Succinct mode which produces only the summary as output.
Verbose = True -> Verbose mode which produces the full output.

Changes are presently available at (https://github.com/karthikreddykuna/DXC-Industrialized-AI-Starter) GitHub repository. We will push the changes to DXC-Industrilialized-AI-Starter main repository after completion of Boot camp.
