### ISSUE TITLE
Add test cases links in contributing guide

### ISSUE THREAD

**Issue by vamsi7behara** [dxc-technology/DXC-Industrialized-AI-Starter#40]
**name** | **title** | **about** | **labels** | **assignees**
-- | -- | -- | -- | --
Transparency Request | Add test cases links in contributing guide

**Describe the area of code that needs more transparency:**
Add test cases links in contributing guide, revisit the contribute guide document, and do the necessary changes.
**Describe the solution you'd like:**
**Describe the alternatives you've considered:**
**Additional context or comments:**

**Comment by madhubandru** [comment]
Revisited contribution guide document and updated with test cases link. Also provided necessary references for Automate test cases execution. 

Updated contribution [guide](https://github.com/dxc-technology/DXC-Industrialized-AI-Starter/blob/master/CONTRIBUTING.md)
