### ISSUE TITLE
Metrics or statistics of differences between raw data and clean data.

### ISSUE THREAD

**Issue by vamsi7behara** [dxc-technology/DXC-Industrialized-AI-Starter#41]
**name** | **title** | **about** | **labels** | **assignees**
-- | -- | -- | -- | --
Transparency Request | metrics or statistics of differences between raw data and clean data.

**Describe the area of code that needs more transparency:**
Display metrics or statistics that show the difference between raw data and clean data. 
**Describe the solution you'd like:**
**Describe the alternatives you've considered:**
**Additional context or comments:**
Show the stats of raw and clean data as different columns 
We should have metrics for categorical and numerical data, should also think about how to handle providing usable metrics for data sets with lots of features.

**Comment by npulagam** [comment]
Showing metrics or statistics of differences between raw data and clean data has been handled.
