### ISSUE TITLE
Rename the variable name in notebook

### ISSUE THREAD

**Issue by vamsi7behara** [dxc-technology/DXC-Industrialized-AI-Starter#42]
**name** | **title** | **about** | **labels** | **assignees**
-- | -- | -- | -- | --
Transparency Request | Rename the variable name in notebook

**Describe the area of code that needs more transparency:**
Rename the variable name representing the dataset after cleaning the data (ex: Raw_data, Clean_data)
**Describe the solution you'd like:**
**Describe the alternatives you've considered:**
**Additional context or comments:**

**Comment by Soujanya8977** [comment]
Renaming variable names is completed .
