### ISSUE TITLE
Include metadata details

### ISSUE THREAD

**Issue by vamsi7behara** [dxc-technology/DXC-Industrialized-AI-Starter#43]
**name** | **title** | **about** | **labels** | **assignees**
-- | -- | -- | -- | --
Transparency Request | Include metadata details

**Describe the area of code that needs more transparency:**
Include metadata details while writing data into MongoDB 
**Describe the solution you'd like:**
**Describe the alternatives you've considered:**
**Additional context or comments:**
Include in the code as a minimum, but best in Mongo
Where did we got the data from, did we ran cleaner on the data 
What version of data is 
Where we stored the data
This is a manual entry

**Comment by Likhil** [comment]
It is completed and will be added to starter after bootcamp
