### ISSUE TITLE
Add logs to the crucial steps

### ISSUE THREAD

**Issue by vamsi7behara** [dxc-technology/DXC-Industrialized-AI-Starter#44]
**name** | **title** | **about** | **labels** | **assignees**
-- | -- | -- | -- | --
Transparency Request | Add logs to the crucial steps

**Describe the area of code that needs more transparency:**
Add logs to the crucial steps that give feasibility to the user to revert changes
**Describe the solution you'd like:**
**Describe the alternatives you've considered:**
**Additional context or comments:**
Add logs to the crucial steps(aggregation) which give the feasibility to the user to revert changes if something goes wrong.
Log storage options, recommend config options (at least) for both Mongo Atlas DB and local storage

**Comment by madhubandru** [comment]
Changes to capture logs for crucial functions in AI-Starter is completed. Changes are integrated with development branch.

Logging functionality is added for capturing

1) Pipeline
2) Experiment Design
3) Micro-service Design
