### ISSUE TITLE
Add the drift function after pipeline

### ISSUE THREAD

**Issue by vamsi7behara** [dxc-technology/DXC-Industrialized-AI-Starter#45]
**name** | **title** | **about** | **labels** | **assignees**
-- | -- | -- | -- | --
Transparency Request | Add the drift function after pipeline

**Describe the area of code that needs more transparency:**
Add the drift function after pipeline
**Describe the solution you'd like:**
**Describe the alternatives you've considered:**
**Additional context or comments:**
Calculate the drift between given two data sets over a period of time or between training sets

**Comment by karthikreddykuna** [comment]
Machine learning models lose their predictive power - a concept known as Model drift.  Changes in the statistical properties of the target variable and the predictors lead to concept drift and data drift, which are leading causes of Model drift. 
Drift detection can be built using scikit-multiflow package. Given every use case, model, the data pattern is different Drift detection will vary in each case. 

Drift detection needs to be done in cloud deployment platforms. Each cloud platform has its own way of the drift detection method. We will create a new issue while working on the model deployment in different cloud platforms along with drift detection as per the roadmap plan.
