### ISSUE TITLE
Provide Auto-ML documentation link in user guide for running models

### ISSUE THREAD

**Issue by vamsi7behara** [dxc-technology/DXC-Industrialized-AI-Starter#46]
**name** | **title** | **about** | **labels** | **assignees**
-- | -- | -- | -- | --
Transparency Request | Provide Auto-ML documentation link

**Describe the area of code that needs more transparency:**
Provide Auto-ML documentation link in the user guide for running models
**Describe the solution you'd like:**
**Describe the alternatives you've considered:**
**Additional context or comments:**
If possible we should provide an easy way to expose deep links to the specific algorithms as part of our way to support Data Scientist making their work explainable

**Comment by karthikreddykuna** [comment]
The auto-ML documentation link was included in the DXC-Industrialized-AI-Starter Notebook.
