### ISSUE TITLE
Indicate the completeness or correctness of the data and show the outliers

### ISSUE THREAD

**Issue by vamsi7behara** [dxc-technology/DXC-Industrialized-AI-Starter#49]
**name** | **title** | **about** | **labels** | **assignees**
-- | -- | -- | -- | --
Transparency Request | indicate the completeness or correctness of the data and show the outliers

**Describe the area of code that needs more transparency:**
indicate the completeness or correctness of the data and show the outliers
**Describe the solution you'd like:**
**Describe the alternatives you've considered:**
**Additional context or comments:**
Logan comments:
Not just visualization, completeness, correctness, outliers, and other metrics should be saved statistics, too. We can’t force others to make their work explainable to an end-user, but we can ensure that their work is capable of being explained if they use our package.

**Comment by npulagam** [comment]
We have completed these changes using the pandas-profiling function and integrated in the development branch.
