### ISSUE TITLE
Research- Add encryption to the published microservice

### ISSUE THREAD

**Issue by vamsi7behara** [dxc-technology/DXC-Industrialized-AI-Starter#50]
**name** | **title** | **about** | **labels** | **assignees**
-- | -- | -- | -- | --
Transparency Request | Add encryption to the published microservice | | Research | 

**Describe the area of code that needs more transparency:**
Add encryption to the published microservice
**Describe the solution you'd like:**
**Describe the alternatives you've considered:**
**Additional context or comments:**
research levels of best-practice security for different types of data. We could offer a parameter mapped to predefined configurations for low, medium, high, and/or extra-high levels of security.

**Comment by Soujanya8977** [comment]
Research on adding encryption to the published micro-service is completed. Here is the update on my research:

We are using algorithmia for generating micro-services. We can add only one layer of encryption to the pickle file which we are sending to to the Algorithmia. Before adding that layer of encryption, we need to generate a secret key in Colab notebook which user needs to store carefully. Every time when user publishes a micro-service, it will generate a new key and user has to save the key for accessing that micro-service.
