### ISSUE TITLE
Unclear "Set up the development environment" instructions

### ISSUE THREAD

**Issue by jonfernandes** [dxc-technology/DXC-Industrialized-AI-Starter#54]
Most of those attending the DXC-Industralized AI course have not used Colab before.
Some of the instructions for getting started in the "Set up the development environment" could be clearer.
e.g. "This code installs all the packages you'll need. Run it first."
Most people who have not used Colab before would not know how to do this.

**Comment by karthikreddykuna** [comment]
@jonfernandes Thanks for the pull request. The guidelines say to restart the runtime once after installing DXC_Industrilized_AI_Starter library. If the restart is done after importing the package, we cannot use the functions from the library. The factory reset will remove the installed DXC_Industrialized_AI_Starter from the memory. So this is not advisable.

Series of steps to follow:

! pip install DXC-Industrialized-AI-Starter.
Restart runtime
from dxc import ai
use functions from ai
Hope it helps. Thanks!
