### ISSUE TITLE
List of available data sets not available

### ISSUE THREAD

**Issue by jerryaoverton** [dxc-technology/DXC-Industrialized-AI-Starter#68]
The link in the example that is supposed to list available data sets is broken

**Comment by madhubandru** [comment]
Hi Jerry,

Previous link provided in example notebook pointed to dataset documentation. Now this is fixed and link in [example notebook for datasets](https://github.com/dxc-technology/DXC-Industrialized-AI-Starter/blob/master/Examples/datasets_in_DXC_Industrialized_AI_Starter.ipynb) will point to GitHub datasets folder.

Thanks

**Comment by npulagam** [comment]
This issue has been resolved, so closing it.
