### ISSUE TITLE
Publishing a microservice of a custom model

### ISSUE THREAD

**Issue by jerryaoverton** [dxc-technology/DXC-Industrialized-AI-Starter#7]
In the documentation can you show an example of publishing a microservice from a custom model instead of a model generated from run_experiment() function? The custom model could be something as simple as a function that adds two number or appends text to an input.

**Comment by Soujanya8977** [comment]
Work in  progress.

**Comment by Soujanya8977** [comment]
Wrote script for publishing a microservice of a custom model and merged it into master branch.
