### ISSUE TITLE
Develop a function to download datasets directly from DXC public github 

### ISSUE THREAD

**Issue by Amarify** [dxc-technology/DXC-Industrialized-AI-Starter#73]
Reasons to implement

1. User has the flexibility to download only required datasets.
2. Reduce the AI starter library size by moving all datasets to DXC public GitHub and providing user a flexibility to download.

**Comment by npulagam** [comment]
This is completed, so closing the issue.

**Comment by madhubandru** [comment]
Yes, changes are merged under pull request #74
