### ISSUE TITLE
Add separator parameter for reading csv files with ai.read_data_frame_from_local_csv()

### ISSUE THREAD

**Issue by lrwilt** [dxc-technology/DXC-Industrialized-AI-Starter#75]
ai.read_data_frame_from_local_csv() needs to be able to accept files with other types of separators. I tried to import a pipe delimited csv file and could not set sep = '|' to be able to read the file

**Comment by npulagam** [comment]
Added the separator parameter for reading csv files with ai.read_data_frame_from_local_csv() function. I have also published the changes to PyPi version 2.3.5.
