### ISSUE TITLE
ai.clean_dataframe() unable to parse date formatted in MM/D/YYYY

### ISSUE THREAD

**Issue by lrwilt** [dxc-technology/DXC-Industrialized-AI-Starter#77]
MM/D/YYYY and MM/DD/YYYY are two popular US date format and it appears the ai.clean_dataframe() function cannot recognize them.

ParserError: Could not match input '10/1/2020' to any of the following formats: YYYY-MM-DD, YYYY-M-DD, YYYY-M-D, YYYY/MM/DD, YYYY/M/DD, YYYY/M/D, YYYY.MM.DD, YYYY.M.DD, YYYY.M.D, YYYYMMDD, YYYY-DDDD, YYYYDDDD, YYYY-MM, YYYY/MM, YYYY.MM, YYYY, W

**Comment by Likhil** [comment]
Changes are made and requested for a review to merge the pull request.

**Comment by Likhil** [comment]
linking the related pull request with the issue
