### ISSUE TITLE
Read data from local excel file in Colab

### ISSUE THREAD

**Issue by vivekbachala** [dxc-technology/DXC-Industrialized-AI-Starter#84]
**Describe the bug**
Trying to upload an excel file (in Colab) but its failing with below error

read_data_frame_from_local_excel_file()
     29         uploaded = files.upload()
     30         excel_file_name = list(uploaded.keys())[0]
---> 31         df = pd.read_excel(io.BytesIO(uploaded[excel_file_name]))
     32         return(df)
     33 

NameError: name 'io' is not defined

**To Reproduce**
1. dataframe = ai.read_data_frame_from_local_excel_file()
2. Browse the excel file  (in Colab) 
3. See error

**Expected behavior**
Dataframe with the Excel data

**Screenshots**

**Additional context**

**Comment by npulagam** [comment]
This issue has been fixed and merged with the master branch. So closing the issue.
