### ISSUE TITLE
distplot is a deprecated

### ISSUE THREAD

**Issue by aumerhadi** [dxc-technology/DXC-Industrialized-AI-Starter#86]
**Describe the bug**
distplot is a deprecated function and will be removed in a future version, we have to find an alternative to replace this function 

**To Reproduce**
1. in the DXC-Industrialized-AI-Starter.ipynb in colab, execute this command ai.plot_distributions(data1)
2. you will get this warning 
`distplot is a deprecated function and will be removed in a future version. Please adapt your code to use either displot (a figure-level function with similar flexibility) or histplot (an axes-level function for histograms).
Pass the following variable as a keyword arg: x. From version 0.12, the only valid positional argument will be data, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
`

**Expected behavior**
WE have to find an alternative for this function

**Screenshots**
![image](https://user-images.githubusercontent.com/2063075/107438176-19155d00-6afe-11eb-88dc-152f7fedb694.png)

**Additional context**
N/A

**Comment by karthikreddykuna** [comment]
Changes were done and published to Github. Changes will be published to production by EOD.
