### ISSUE TITLE
Cant resubmit after rework on badge

### ISSUE THREAD

**Issue by Philipeldh** [dxc-technology/DXC-Industrialized-AI-Starter#88]
After getting a "rework" status on a badge, doing the changes required and then resubmits gets you an error response that an assertion already exists:

`<Response [400]>
{
    "errorMessage": {
        "statusCode": 400,
        "exception": "BadRequest",
        "message": "Assertion already exists",
        "payload": {
            "evidence": "https://colab.research.google.com/drive/1oMUEVLS5x1netqWaL0kAt8FVR-ABeJ4U",
            "lastUpdated": "2021-02-10T15:37:33Z",
            "badge": "Create a Data Story",
            "status": "rework",
            "created": "2021-02-09T16:06:25Z",
            "comments": [
                {
                    "date": "2021-02-10T15:37:33Z",
                    "comment": "Hello, nice work, but for the sample data set area, please upload your data set, not the iris file.",
                    "email": "tlhotak@dxc.com"
                }
            ],
            "email": "peldh@dxc.com",
            "d1": "user:6366a530-391b-41be-bbff-6f372658afef",
            "d2": "badge:dd05bbdf-ad5b-469d-ab2c-4dd218fd68fe",
            "salt": "ecaa9028a8feb321be864bf98ac1ebe6",
            "reviewer": "tlhotak@dxc.com",
            "sk": "assertion",
            "pk": "assertion:93372602-81eb-47dc-bf05-5bc475c276b6"
        }
    }
}` 

![image](https://user-images.githubusercontent.com/22307490/107560749-0a9e7280-6bde-11eb-8d53-01ff85c95b0d.png)

**Comment by npulagam** [comment]
Hi @Philipeldh, Our Team is aware of this error. We are receiving this error from the badger site and we do not have complete control over the badger site. We can not resolve this error from the AI-Starter end without having complete control of the badger platform. To resolve this resubmitting issue, we will delete your Guild badge insertions manually on the badger site. After deleting the badges you can resubmit them from the notebook.

**Comment by npulagam** [comment]
I do not see any pending or rework badges on your name on the badger site. You can submit the remaining badges from the notebook. So closing this issue. Thank you!
