### ISSUE TITLE
[BUG] Pandas.IO.JSON.JSON_Normalize is depreceated, (Build Data Pipeline)

### ISSUE THREAD

**Issue by Philipeldh** [dxc-technology/DXC-Industrialized-AI-Starter#89]
**Describe the bug**
the lib pandas.io.json.json_normalize is depreceated, recommendation to use pandas.json_normalize instead

**To Reproduce**
1. Go to build data pipe line in Collab
2. Click on the cell #TODO: Define the code needed to refine the raw data
3. Run cell

**Expected behavior**
no error from Pandas lib

**Screenshots**
![image](https://user-images.githubusercontent.com/22307490/107687388-b612fa00-6ca6-11eb-996f-30dde1dcec36.png)

**Comment by Soujanya8977** [comment]
Changes are implemented and merged with the master branch.
