### ISSUE TITLE
[BUG] Error when importing ai package

### ISSUE THREAD

**Issue by Chandra-Ananthapatnayakuni** [dxc-technology/DXC-Industrialized-AI-Starter#93]
**Describe the bug**
Error occurred when trying to import ai from dxc

**To Reproduce**
1. used pip to install ai starter package
2. from dxc import ai
3. error

**Expected behavior**
ai was getting loaded earlier

**Screenshots**
![image](https://user-images.githubusercontent.com/29919236/108981508-ccf81a00-76b2-11eb-924b-a07f5b4d1972.png)

**Comment by karthikreddykuna** [comment]
Hi @Chandra-Ananthapatnayakuni ,
The issue is because of changes in the dependent libraries. We identified the issue and a new version will be released today with the fix. Meanwhile to continue with your work you can install the latest changes using the following command. 
! pip install git+https://github.com/dxc-technology/DXC-Industrialized-AI-Starter.git

**Comment by Chandra-Ananthapatnayakuni** [comment]
The error still exists, even though I tried to install from GIT repository

![image](https://user-images.githubusercontent.com/29919236/109046477-cab9ae00-76fa-11eb-8242-33d68b1e7a2c.png)

**Comment by karthikreddykuna** [comment]
@Chandra-Ananthapatnayakuni, Could you please factory reset the runtime and try again. Seems that the previous version still exists.

**Comment by Chandra-Ananthapatnayakuni** [comment]
ai package got loaded now.
But the problem seem to be in ai.read_data_frame_from_remote_csv
It returns a **LIST** instead of a **DATAFRAME**

![image](https://user-images.githubusercontent.com/29919236/109158247-2175c500-7799-11eb-861e-77ee4d19483b.png)

**Comment by keohan** [comment]
> @Chandra-Ananthapatnayakuni, Could you please factory reset the runtime and try again. Seems that the previous version still exists.

This resolves the immediate issue, but it appears other dependencies are missing as errors are encountered at:

- ai.load_data_details
![image](https://user-images.githubusercontent.com/36521087/109188047-7ea15480-7760-11eb-99d6-ec4531e0b13c.png)

- ai.clean_dataframe
![image](https://user-images.githubusercontent.com/36521087/109188186-a8f31200-7760-11eb-99ae-243127615bbc.png)

**Comment by karthikreddykuna** [comment]
@Chandra-Ananthapatnayakuni Could you please share the notebook with us.

**Comment by keohan** [comment]
> @Chandra-Ananthapatnayakuni

Everyone should be able to view at: https://colab.research.google.com/drive/1xNueMkbkDbbK7Q5J6rl6IBRXrcLjbm7F?usp=sharing

**Comment by Chandra-Ananthapatnayakuni** [comment]
now it looks like the problem is fixed.
**FAILS**: ! pip install git+https://github.com/dxc-technology/DXC-Industrialized-AI-Starter.git
**Success**: ! pip install DXC-Industrialized-AI-Starter
